sudo: required
services:
    - docker
before_install:
    - docker build -t sppiotrowski/client-test -f ./client/Dockerfile.dev ./client
script:
    - docker run sppiotrowski/client-test yarn test -- --coverage
after_success:
    - docker build -t sppiotrowski/multi-client ./client
    - docker build -t sppiotrowski/multi-nginx ./nginx
    - docker build -t sppiotrowski/multi-server ./server
    - docker build -t sppiotrowski/multi-worker ./worker
    # log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push sppiotrowski/multi-client
    - docker push sppiotrowski/multi-nginx
    - docker push sppiotrowski/multi-server
    - docker push sppiotrowski/multi-worker
